// Mapping wilaya -> frais de livraison (bureau de la société de livraison)
// Prix unique : 500 DA pour toutes les wilayas
export const WILAYA_SHIPPING = [
  { value: 'Adrar', label: 'Adrar (500 DA - bureau)', shippingDa: 500 },
  { value: 'Chlef', label: 'Chlef (500 DA - bureau)', shippingDa: 500 },
  { value: 'Laghouat', label: 'Laghouat (500 DA - bureau)', shippingDa: 500 },
  { value: 'Oum El Bouaghi', label: 'Oum El Bouaghi (500 DA - bureau)', shippingDa: 500 },
  { value: 'Batna', label: 'Batna (500 DA - bureau)', shippingDa: 500 },
  { value: 'Béjaïa', label: 'Béjaïa (500 DA - bureau)', shippingDa: 500 },
  { value: 'Biskra', label: 'Biskra (500 DA - bureau)', shippingDa: 500 },
  { value: 'Béchar', label: 'Béchar (500 DA - bureau)', shippingDa: 500 },
  { value: 'Blida', label: 'Blida (500 DA - bureau)', shippingDa: 500 },
  { value: 'Bouira', label: 'Bouira (500 DA - bureau)', shippingDa: 500 },
  { value: 'Tamanrasset', label: 'Tamanrasset (500 DA - bureau)', shippingDa: 500 },
  { value: 'Tébessa', label: 'Tébessa (500 DA - bureau)', shippingDa: 500 },
  { value: 'Tlemcen', label: 'Tlemcen (500 DA - bureau)', shippingDa: 500 },
  { value: 'Tiaret', label: 'Tiaret (500 DA - bureau)', shippingDa: 500 },
  { value: 'Tizi Ouzou', label: 'Tizi Ouzou (500 DA - bureau)', shippingDa: 500 },
  { value: 'Alger', label: 'Alger (500 DA - bureau)', shippingDa: 500 },
  { value: 'Djelfa', label: 'Djelfa (500 DA - bureau)', shippingDa: 500 },
  { value: 'Jijel', label: 'Jijel (500 DA - bureau)', shippingDa: 500 },
  { value: 'Sétif', label: 'Sétif (500 DA - bureau)', shippingDa: 500 },
  { value: 'Saïda', label: 'Saïda (500 DA - bureau)', shippingDa: 500 },
  { value: 'Skikda', label: 'Skikda (500 DA - bureau)', shippingDa: 500 },
  { value: 'Sidi Bel Abbès', label: 'Sidi Bel Abbès (500 DA - bureau)', shippingDa: 500 },
  { value: 'Annaba', label: 'Annaba (500 DA - bureau)', shippingDa: 500 },
  { value: 'Guelma', label: 'Guelma (500 DA - bureau)', shippingDa: 500 },
  { value: 'Constantine', label: 'Constantine (500 DA - bureau)', shippingDa: 500 },
  { value: 'Médéa', label: 'Médéa (500 DA - bureau)', shippingDa: 500 },
  { value: 'Mostaganem', label: 'Mostaganem (500 DA - bureau)', shippingDa: 500 },
  { value: 'M\'Sila', label: 'M\'Sila (500 DA - bureau)', shippingDa: 500 },
  { value: 'Mascara', label: 'Mascara (500 DA - bureau)', shippingDa: 500 },
  { value: 'Ouargla', label: 'Ouargla (500 DA - bureau)', shippingDa: 500 },
  { value: 'Oran', label: 'Oran (500 DA - bureau)', shippingDa: 500 },
  { value: 'El Bayadh', label: 'El Bayadh (500 DA - bureau)', shippingDa: 500 },
  { value: 'Illizi', label: 'Illizi (500 DA - bureau)', shippingDa: 500 },
  { value: 'Bordj Bou Arréridj', label: 'Bordj Bou Arréridj (500 DA - bureau)', shippingDa: 500 },
  { value: 'Boumerdès', label: 'Boumerdès (500 DA - bureau)', shippingDa: 500 },
  { value: 'El Tarf', label: 'El Tarf (500 DA - bureau)', shippingDa: 500 },
  { value: 'Tindouf', label: 'Tindouf (500 DA - bureau)', shippingDa: 500 },
  { value: 'Tissemsilt', label: 'Tissemsilt (500 DA - bureau)', shippingDa: 500 },
  { value: 'El Oued', label: 'El Oued (500 DA - bureau)', shippingDa: 500 },
  { value: 'Khenchela', label: 'Khenchela (500 DA - bureau)', shippingDa: 500 },
  { value: 'Souk Ahras', label: 'Souk Ahras (500 DA - bureau)', shippingDa: 500 },
  { value: 'Tipaza', label: 'Tipaza (500 DA - bureau)', shippingDa: 500 },
  { value: 'Mila', label: 'Mila (500 DA - bureau)', shippingDa: 500 },
  { value: 'Aïn Defla', label: 'Aïn Defla (500 DA - bureau)', shippingDa: 500 },
  { value: 'Naâma', label: 'Naâma (500 DA - bureau)', shippingDa: 500 },
  { value: 'Aïn Témouchent', label: 'Aïn Témouchent (500 DA - bureau)', shippingDa: 500 },
  { value: 'Ghardaïa', label: 'Ghardaïa (500 DA - bureau)', shippingDa: 500 },
  { value: 'Relizane', label: 'Relizane (500 DA - bureau)', shippingDa: 500 },
  { value: 'Timimoun', label: 'Timimoun (500 DA - bureau)', shippingDa: 500 },
  { value: 'Bordj Badji Mokhtar', label: 'Bordj Badji Mokhtar (500 DA - bureau)', shippingDa: 500 },
  { value: 'Ouled Djellal', label: 'Ouled Djellal (500 DA - bureau)', shippingDa: 500 },
  { value: 'Béni Abbès', label: 'Béni Abbès (500 DA - bureau)', shippingDa: 500 },
  { value: 'In Salah', label: 'In Salah (500 DA - bureau)', shippingDa: 500 },
  { value: 'In Guezzam', label: 'In Guezzam (500 DA - bureau)', shippingDa: 500 },
  { value: 'Touggourt', label: 'Touggourt (500 DA - bureau)', shippingDa: 500 },
  { value: 'Djanet', label: 'Djanet (500 DA - bureau)', shippingDa: 500 },
  { value: 'El M\'Ghair', label: 'El M\'Ghair (500 DA - bureau)', shippingDa: 500 },
  { value: 'El Meniaa', label: 'El Meniaa (500 DA - bureau)', shippingDa: 500 },
]

export function findShipping(wilaya: string): number {
  return WILAYA_SHIPPING.find((w) => w.value === wilaya)?.shippingDa ?? 0
}